name: sildaprayona_simplysync
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.2
  path: ^1.9.0
  file_picker: ^10.2.0
  dio: ^5.4.0
  dartssh2: ^2.9.0
  ftpconnect: ^2.0.7
  webdav_client: ^1.2.2
  workmanager: ^0.7.0
  flutter_local_notifications: ^19.3.0
  sqflite: ^2.3.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  crypto: ^3.0.3
  intl: ^0.20.2
  translator: ^1.0.4+1
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
